version: '2.4'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example_sa
      POSTGRES_DB: exampledb
    ports:
      - 5432:5432